hostname = *.eastmoney.com, emads.eastmoney.com

# 东方财富 - 脚本处理开屏和弹窗
^https?:\/\/emads?\.eastmoney\.com\/api\/advert\/get_(advert|splash_config|popup_list) url script-response-body https://raw.githubusercontent.com/KimpoHung/Hello-QuantumultX/main/scripts/dfcf_purify.js

# 东方财富 - 直接拦截静态广告请求
^https?:\/\/emads?\.eastmoney\.com\/api\/advert\/get_ad_config url reject-200
